### ISSUE TITLE
radosgw dbstore: impossible to manage users

### ISSUE THREAD

**Issue by trociny** [aquarist-labs/s3gw-core#3]
Currently, when running radosgw with dbstore backend, it will create "testid" user automatically with the hardcoded keys [1]:
```
access_key = 0555b35654ad1656d804
secret_key = h7GhxuBLTrlhVUyxSPUKUV8r/2EI4ngqJxD7iBdBYLhwluN30JaT3Q==
```

So for now we may use this user for testing and demo but eventually we would need to manage the users somehow.

Currently the radosgw-admin tool is hardcoded to use rados backend only, so eventually it should be improved to support the other backends.

As a quick solution (workaround) we may write a script that would manage users in the sqlite. E.g to change the access key for the existing user "testid" one can run:
```
adonis:~/ceph/ceph.upstream/build% sqlite3 default_ns.db
sqlite> UPDATE default_ns_user_table SET AccessKeysID = "0555b35654ad1656d805" WHERE UserID = "testid";
```

[1] https://github.com/ceph/ceph/blob/2d1c480f5a29af590686b7acb58629a3937f8522/src/rgw/rgw_sal.cc#L131

**Comment by jecluis** [comment]
@0xavi0 assigning this to you. You might want to split this into smaller issues though, up to you.

**Comment by votdev** [comment]
FYI, there are various environment variables that can be used to customize user values, e.g.:
- RGW_DEFAULT_USER_ID
- RGW_DEFAULT_USER_DISPLAY_NAME
- RGW_DEFAULT_USER_EMAIL
- RGW_DEFAULT_USER_ACCESS_KEY
- RGW_DEFAULT_USER_SECRET_KEY
- RGW_DEFAULT_USER_CAPS
- RGW_DEFAULT_USER_SYSTEM
- RGW_DEFAULT_USER_ASSUMED_ROLE_ARN

You can set them for example when starting the container: `podman run --replace --name=s3gw -it -p 7480:7480 -e RGW_DEFAULT_USER_SYSTEM=1 -e RGW_DEFAULT_USER_CAPS="roles=*;users=*;buckets=*" localhost/s3gw --rgw-backend-store dbstore --debug-rgw 20`

**Comment by jhmarina** [comment]
Since this issue was created, we've shifted to using `sfs` instead of `dbstore`. User management has been implemented in this PR https://github.com/aquarist-labs/ceph/pull/15
