### ISSUE TITLE
radosgw dbstore: works incorrectly with s3cmd "--recursive" commands

### ISSUE THREAD

**Issue by trociny** [aquarist-labs/s3gw-core#5]
So currently, one may just start radosgw with dbstore backend, e.g:
```
  ./bin/radosgw --rgw-backend-store=dbstore -i foo --no-mon-config
```

And as it automatically creates the test user, it will work with s3cmd with a config like below:
```
adonis:~/ceph/ceph.upstream/build% cat s3config
[default]
host_base = localhost:7480
access_key = 0555b35654ad1656d804
secret_key = h7GhxuBLTrlhVUyxSPUKUV8r/2EI4ngqJxD7iBdBYLhwluN30JaT3Q==
host_bucket = anything.with.three.dots
enable_multipart = True
recursive = False
use_https = False
```

It works for simple commands like put, rm:
```
adonis:~/ceph/ceph.upstream/build% s3cmd --config=s3config mb s3://s3cmd-demo/ 
Bucket 's3://s3cmd-demo/' created
adonis:~/ceph/ceph.upstream/build% s3cmd --config=s3config put /etc/passwd s3://s3cmd-demo/
upload: '/etc/passwd' -> 's3://s3cmd-demo/passwd'  [1 of 1]
 2379 of 2379   100% in    0s   305.21 kB/s  done
adonis:~/ceph/ceph.upstream/build% s3cmd --config=s3config rm s3://s3cmd-demo/passwd          
delete: 's3://s3cmd-demo/passwd'
```

But for the commands with `--recursive` command some weird things happen. E.g. the `ls` command returns the list recursively when it is run without `--recursive`. Or if one run `rm --recursive` for some bucket subtree it will delete all files in the bucket, not just the subtree.

I don't see this behavior with the same config for radosgw with rados backend.

**Comment by giubacc** [comment]
From a first investigation of the issue, it seems that this is more related to the `ls` command.
`DELETE` with `--recursive` relies mainly on the output produced by the `ls` command; and this, for dbstore, is producing a wrong set.

For example if you feed two different backend, one using `rados` and the second using `dbstore`, with the same data, you will get two different output for `ls`.

`RADOS`

```
s3cmd --no-ssl -c s3cmd.cfg ls s3://test/inner/

2022-04-08 15:17            0  s3://test/inner/myf3
2022-04-08 15:17            0  s3://test/inner/myf4
2022-04-08 15:17            0  s3://test/inner/myf5
2022-04-08 15:17           25  s3://test/inner/myfile
```

`DBSTORE`

```
s3cmd --no-ssl -c s3cmd.cfg ls s3://test/inner/

2022-04-08 15:16            0  s3://test/inner/myf3
2022-04-08 15:16            0  s3://test/inner/myf4
2022-04-08 15:16            0  s3://test/inner/myf5
2022-04-08 15:16           25  s3://test/inner/myfile
2022-04-08 15:16            0  s3://test/myf6
2022-04-08 15:16            0  s3://test/myf7
```

As you can see, `dbstore` is wrongly returning also the parent's objects, those inside the parent bucket.

Another notable difference:

`RADOS`

```
s3cmd --no-ssl -c s3cmd.cfg ls s3://test

                          DIR  s3://test/inner/
2022-04-08 15:17            0  s3://test/myf6
2022-04-08 15:17            0  s3://test/myf7
```

`DBSTORE`

```
s3cmd --no-ssl -c s3cmd.cfg ls s3://test

2022-04-08 15:16            0  s3://test/inner/myf3
2022-04-08 15:16            0  s3://test/inner/myf4
2022-04-08 15:16            0  s3://test/inner/myf5
2022-04-08 15:16           25  s3://test/inner/myfile
2022-04-08 15:16            0  s3://test/myf6
2022-04-08 15:16            0  s3://test/myf7
```
 
It seems that `ls` for `rados` is able to recognize a bucket and presenting it as a `DIR`; this is not happening with `dbstore`.
Next week I will continue to investigate on this.

**Comment by giubacc** [comment]
@jecluis do you suggest to open a more specific issue related to `ls` ?
I guess that every command that somehow _relies_ on `ls` to work could potentially be affected by this.

**Comment by giubacc** [comment]
proposed [downstream PR](https://github.com/aquarist-labs/ceph/pull/3)  will be superseded by this [upstream PR](https://github.com/ceph/ceph/pull/45909)
