### ISSUE TITLE
Testing code

### ISSUE THREAD

**Issue by jhmarina** [aquarist-labs/s3gw-core#64]
In the last [Strategy meeting](https://confluence.suse.com/pages/viewpage.action?pageId=1011089830) the team disussed the need to implement tests. 

Since the team wants to build the habit of releasing regularly, implementing tests is important, since it'll give us the confidence that everything works.

We're handling complex bits of code and not having any tests may be risky. The team feels that we need to at least implement smoke tests.

**Comment by jecluis** [comment]
Basic smoke tests were introduced via #66. We do need to expand on these, but I'd think, for the purposes of this ticket, this has been achieved.
