### ISSUE TITLE
rgw/sfs: move from a path based to sqlite based store

### ISSUE THREAD

**Issue by 0xavi0** [aquarist-labs/s3gw-core#90]
Right now `sfs` is based primarily on file paths, from which it loads metadata (stored in json files), and also lists the objects in a bucket based on object maps (also stored in json files).

We need to move the metadata from json files to sqlite. And the buckets representation from directories to sqlite entries.

**Comment by jecluis** [comment]
Achieved with aquarist-labs/ceph#18 and aquarist-labs/ceph#19.
