### ISSUE TITLE
s3gw: stress tester

### ISSUE THREAD

**Issue by jecluis** [aquarist-labs/s3gw-core#93]
Would be nice to have a tool that issued several different operations (GET/PUT/DELETE/etc) on a small set of objects, with several threads. The objective is checking if we hit any corner cases where operations ended up getting unexpected results. This way we could validate whether we are doing the right thing in the backend.

My worries are mostly around concurrent GET/PUT with DELETE.

**Comment by giubacc** [comment]
@jecluis I can take this; I would like to try to experiment a bit with Go for this, any objections?
